"""Utilities __init__.py"""

from timetable_sa.examples.timetabling.utils.time import (
    time_to_minutes,
    minutes_to_time, 
    calculate_end_time,
    parse_time_range,
    get_period_number,
    is_morning_class,
    is_evening_class,
    is_overlap,
    format_duration,
)
from timetable_sa.examples.timetabling.utils.prayer_times import (
    PRAYER_TIMES,
    PRAYER_PERIODS,
    FRIDAY_PRAYER_PERIODS,
    is_in_prayer_time,
    get_prayer_time_for_day,
    DAYS_OF_WEEK,
    MORNING_CLASS,
    EVENING_CLASS,
)
from timetable_sa.examples.timetabling.utils.timeslot_generator import (
    TimeSlotGenerator,
    generate_ts_slots,
    generate_default_time_slots,
    generate_morning_slots,
    generate_evening_slots,
)
from timetable_sa.examples.timetabling.utils.initial_solution import (
    create_initial_state,
    create_greedy_initial_state,
    create_greedy_initial_state_v2,
    clone_state,
)
from timetable_sa.examples.timetabling.utils.constraint_helpers import (
    group_by_room,
    group_by_lecturer,
    group_by_prodi,
    group_by_day,
    get_entries_at_time,
    check_time_overlap,
    count_conflicts,
    calculate_room_utilization,
    calculate_lecturer_workload,
)
from timetable_sa.examples.timetabling.utils.class_helper import (
    get_lecturers_for_class,
    needs_lab,
    get_preferred_rooms,
    get_class_identifier,
    group_classes_by_prodi,
    group_classes_by_kelas,
    filter_classes_by_prodi,
    filter_classes_by_lecturer,
    filter_classes_by_type,
    filter_lab_classes,
    count_total_participants,
    count_total_sks,
    get_unique_lecturers,
    get_class_summary,
    has_class_overlap,
)
from timetable_sa.examples.timetabling.utils.room_availability import (
    RoomAvailabilityChecker,
    find_available_slot,
)
from timetable_sa.examples.timetabling.utils.room_constants import (
    ROOM_TYPE_THEORY,
    ROOM_TYPE_LAB,
    get_room_capacity_tier,
    get_room_type_config,
    get_available_room_types,
    is_valid_room_type,
)
from timetable_sa.examples.timetabling.utils.slot_validator import (
    validate_time_slot,
    validate_time_slots,
    check_slot_conflict,
    find_conflicting_slots,
    get_period_time_range,
    generate_standard_slot,
    are_slots_equivalent,
    sort_slots_by_time,
    VALID_DAYS,
    VALID_PERIODS,
)

__all__ = [
    # Time functions
    "time_to_minutes",
    "minutes_to_time",
    "calculate_end_time",
    "parse_time_range",
    "get_period_number",
    "is_morning_class",
    "is_evening_class",
    "is_overlap",
    "format_duration",
    # Prayer times
    "PRAYER_TIMES",
    "PRAYER_PERIODS",
    "FRIDAY_PRAYER_PERIODS",
    "is_in_prayer_time",
    "get_prayer_time_for_day",
    "DAYS_OF_WEEK",
    "MORNING_CLASS",
    "EVENING_CLASS",
    # Time slot generation
    "TimeSlotGenerator",
    "generate_ts_slots",
    "generate_default_time_slots",
    "generate_morning_slots",
    "generate_evening_slots",
    # Initial state
    "create_initial_state",
    "create_greedy_initial_state",
    "create_greedy_initial_state_v2",
    "clone_state",
    # Constraint helpers
    "group_by_room",
    "group_by_lecturer",
    "group_by_prodi",
    "group_by_day",
    "get_entries_at_time",
    "check_time_overlap",
    "count_conflicts",
    "calculate_room_utilization",
    "calculate_lecturer_workload",
    # Class helpers
    "get_lecturers_for_class",
    "needs_lab",
    "get_preferred_rooms",
    "get_class_identifier",
    "group_classes_by_prodi",
    "group_classes_by_kelas",
    "filter_classes_by_prodi",
    "filter_classes_by_lecturer",
    "filter_classes_by_type",
    "filter_lab_classes",
    "count_total_participants",
    "count_total_sks",
    "get_unique_lecturers",
    "get_class_summary",
    # Room availability
    "RoomAvailabilityChecker",
    "find_available_slot",
    # Room constants
    "ROOM_TYPE_THEORY",
    "ROOM_TYPE_LAB",
    "get_room_capacity_tier",
    "get_room_type_config",
    "get_available_room_types",
    "is_valid_room_type",
    # Slot validator
    "validate_time_slot",
    "validate_time_slots",
    "check_slot_conflict",
    "find_conflicting_slots",
    "get_period_time_range",
    "generate_standard_slot",
    "are_slots_equivalent",
    "sort_slots_by_time",
    "VALID_DAYS",
    "VALID_PERIODS",
]
